name: acoist
version: 0.1.1
description: >
  “Acoist: Acolyte - Integration system with Server Transmission” - An Integration Toolkit for to transmit VCS-managed resources such as source codes or medium to FTP-connected server that is mainly ICT system in churches or other christian organizations.
author: Haruka Sato <as.he.that.doth.serve@gmail.com>
homepage: https://www.jelckamata.com/
repository: https://github.com/jelckamata/Acoist.git
environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  ini: ^2.1.0
  glob: ^2.1.3
  git_clone: ^1.2.0
  ftpconnect: ^2.0.10
executables:
  acoist: ci.dart